
services:
  - type: worker
    name: tephtona-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m Tepthon"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
